### PR TITLE
Requesting signoff for flood subsystem

### PR DESCRIPTION
**Pull request by Drippin101**

### CODE REVIEW

**Review by JesseTNRoberts — COMMENTED** [review]
This only checks for water in a specific location. How is this sufficient to detect the presence of water in the house for a warranty purpose?

This is not a good faith effort. The constraints are very lacking.

**Comment by Drippin101** [comment]
Added constraints, added where sensors should be placed to give a more accurate view

**Review by JesseTNRoberts — COMMENTED** [review]
You haven't shown that the configuration of sensor and microcontroller will function together. You have to show that the system can get the necessary information into the MC.

**Comment by Drippin101** [comment]
Added beneath schematic diagram: Sensor outputs an analog value, esp32 gpio1 pin has an ADC. This will allow the sensor and microcontroller to interface.

**Comment by Drippin101** [comment]
Added that the water sensor has outputs 0-3.3 volts and the 12-bit ADC on the ESP converts the voltage to a value of 0-4095.

**Review by JesseTNRoberts — COMMENTED** [review]
I don't see any of the discussion on analog accuracy and how the signal gets to the esp.

**Comment by Drippin101** [comment]
Added that the sensor will alert if any amount of water is detected and will be scaled up to record in 5 mm steps.

**Review by JesseTNRoberts — COMMENTED** [review]
comments in person: noise considerations

**Comment by Drippin101** [comment]
added simulation of noise

**Comment by Drippin101** [comment]
added calculation of number of steps, volts per step etc. to find out if filter was good enough

**Review by JesseTNRoberts — APPROVED** [review]

**Pull request merged**
