### PR TITLE
Requesting Signoff for Fire Subsystem

### PR DESCRIPTION
**Pull request by jacksonrwoodard**

### CODE REVIEW

**Review by JesseTNRoberts — COMMENTED** [review]
No temperature resolution consideration. This doesn't give a physical design for the subsystem. That must be present for this to be buildable.

**Review by JesseTNRoberts — COMMENTED** [review]
It's not clear to me how you know that the design will work. How do you know that the connections you have made are correct? 

In the analysis, don't write large paragraphs. The purpose is to prove it will work, not to argue that it will.

**Review by JesseTNRoberts — COMMENTED** [review]
Separate the analysis out of single large paragraphs. Deal with consideration at a time and don't lump them together. Paragraphs aren't helpful in technical analysis contexts because they make the information impenetrable.

**Comment by jacksonrwoodard** [comment]
Analysis was fixed and added a 3D model of the enclosure being used for the module.

**Review by JesseTNRoberts — COMMENTED** [review]
This looks good. Can you add the sensor into the 3d model so that we are sure it will fit appropriately and will mount.

**Comment by jacksonrwoodard** [comment]
> This looks good. Can you add the sensor into the 3d model so that we are sure it will fit appropriately and will mount.

The 3D model has been updated.

**Pull request merged**
