### PR TITLE
Requesting Power Module Signoff

### PR DESCRIPTION
**Pull request by jacksonrwoodard**

### CODE REVIEW

**Review by JesseTNRoberts — COMMENTED** [review]
I don't see part numbers for some of the items. Also, no appropriate analysis proving this design works.

**Review by JesseTNRoberts — COMMENTED** [review]
How do you know that the battery pack will charge in this configuration? Also, is it ok to constantly charge (you can't disconnect at full charge)? How long will things last on this? You haven't addressed this. You have to meet all the requirements from previous systems.

**Comment by imacole** [comment]
Most of this information is based on the emails and in person conversation that I had with Dr. Bhattacharya. I am not sure how to reference emails and direct conversation so it wasn't included as references on here. We were going to ask about that information yesterday, but we didn't have class. The voltage divider circuit is what Dr. Bhattacharya recommended for continual operation of the circuit with no down time, the battery has a BMS to prevent overcharging, and this type of battery should last 10 years.

**Review by JesseTNRoberts — COMMENTED** [review]
Good job leveraging Dr. Bhattacharya's expertise!

**Pull request merged**
